train:
  tensorboard_path: ./logs/
  log_interval_steps: 10
  epochs: 300
  optimizer:
    lr: 5e-4
    betas: [0.9, 0.999]
    eps: 1e-8
  seed: 42
  monitor: val_loss
  monitor_mode: min

dataset:
  type: avmnist
  params:
    data_dir: ../_MFAS/avmnist
    batch_size: 32
    num_workers: -1

model:
  type: avmnist_mixer
#  dropout: 0.5
  modalities:
    classification:
      num_classes: 10
    image:
      in_channels: 1
      hidden_dim: 32
      patch_size: 4
      image_size: [28, 28]
      token_dim: 32
      channel_dim: 128
      num_mixers: 2
    audio:
      in_channels: 1
      hidden_dim: 32
      patch_size: 16
      image_size: [ 112, 112 ]
      token_dim: 32
      channel_dim: 128
      num_mixers: 2
    multimodal:
      hidden_dim: 32
      token_dim: 16
      channel_dim: 256
      num_mixers: 2
