train:
  tensorboard_path: ./logs/
  log_interval_steps: 10
  epochs: 100
  optimizer:
    lr: 5e-4
    betas: [0.9, 0.999]
    eps: 1e-8
  seed: 42
  monitor: val_loss
  monitor_mode: min

dataset:
  type: mmimdb
  params:
    data_dir: ../output/
    batch_size: 32
    num_workers: -1
    max_seq_len: &max_seq_len 160

    projection:
      num_hashes: 64
      feature_size: &feature_size 1024
      window_size: &window_size 1

    vocab:
      tokenizer_type: wordpiece
      tokenizer:
        vocab: ./wordpiece/mbert_vocab.txt
        lowercase: false
        strip_accents: false
        clean_text: false
      vocab_path: vocab.npy

model:
  type: mmimdb_convnet
  dropout: 0.5
  modalities:
    bottleneck:
      window_size: *window_size
      feature_size: *feature_size
      hidden_dim: &hidden_dim 768
    text:
      num_mixers: 1
      max_seq_len: *max_seq_len
      hidden_dim: *hidden_dim
      mlp_hidden_dim: 512
    classification:
      hidden_dim: *hidden_dim
      proj_dim: *hidden_dim
      num_classes: 23
    image:
      in_channels: 3
      hidden_dim: 768
      patch_size: 16
      image_size: [160, 256]
      num_mixers: 1
      token_dim: 32
      channel_dim: 3072
    multimodal:
      hidden_dim: 768 # 768
      num_mixers: 1
      token_dim: 32
      channel_dim: 64 # 512