train:
  tensorboard_path: ./logs/
  log_interval_steps: 10
  epochs: 100
  optimizer:
    lr: 5e-4
    betas: [0.9, 0.999]
    eps: 1e-8
  seed: 42
  monitor: val_loss
  monitor_mode: min

dataset:
  type: imagenet
  params:
    data_dir: ../data/imagenet/ILSVRC/Data/CLS-LOC/
    batch_size: 32
    num_workers: -1

model:
  type: imagenet_pooler
  dropout: 0.5
  modalities:
    classification:
      num_classes: 1000
    image:
      in_channels: 3
      hidden_dims: [1024, 512, 256, 128, 64, 32]
      patch_size: 16
      image_size: [224, 224]
      num_mixers: 1
      token_dim: 32
      channel_dim: 3072
