train:
  tensorboard_path: ./logs/
  log_interval_steps: 10
  epochs: 300
  optimizer:
    lr: 1e-4
    betas: [0.9, 0.999]
    eps: 1e-8
    weight_decay: 0.0
  seed: 42
  monitor: val_loss
  monitor_mode: min

dataset:
  type: AVMnistDataModule
  params:
    data_dir: ../data/avmnist_orig/avmnist
    batch_size: 32
    num_workers: -1

model:
  type: AVMnistMixerMultiLoss
  dropout: 0.5
  modalities:
    classification:
      num_classes: 10
    image:
      block_type: DynaMixer
      in_channels: 1
      hidden_dim: 256
      patch_size: 4
      image_size: [28, 28]
      num_head: 8
      num_mixers: 8
      reduced_dim: 2
    audio:
      block_type: DynaMixer
      in_channels: 1
      hidden_dim: 256
      patch_size: 16
      image_size: [112, 112]
      num_head: 8
      num_mixers: 8
      reduced_dim: 2
    multimodal:
      block_type: FusionDynaMixer
      fusion_function: MaxFusion
      hidden_dim: 256
      num_head: 8
      num_mixers: 4
      reduced_dim: 2
