train:
  tensorboard_path: ./logs/
  log_interval_steps: 10
  epochs: 300
  optimizer:
    lr: 5e-4
    betas: [0.9, 0.999]
    eps: 1e-8
  seed: 42
  monitor: val_loss
  monitor_mode: min

dataset:
  type: avmnist
  params:
    data_dir: ../data/avmnist_orig/avmnist
    batch_size: 32
    num_workers: -1

model:
  type: avmnist_gmlp
  mute: audio
#  dropout: 0.5
  modalities:
    classification:
      num_classes: 10
    image:
      in_channels: 1
      patch_size: 4
      image_size: [28, 28]
      d_model: 128
      d_ffn: 768
      n_blocks: 30
    audio:
      in_channels: 1
      patch_size: 16
      image_size: [112, 112]
      d_model: 128
      d_ffn: 768
      n_blocks: 30
    multimodal:
      d_model: 128
      d_ffn: 768
      n_blocks: 15
