train:
  tensorboard_path: ./logs/
  log_interval_steps: 10
  epochs: 60
  optimizer:
    lr: 5e-4
    betas: [0.9, 0.999]
    eps: 1e-8
    weight_decay: 0.0
  seed: 42
  monitor: val_loss
  monitor_mode: min

dataset:
  type: AVMnistDataModule
  params:
    data_dir: ../data/avmnist_orig/avmnist
    batch_size: 32
    num_workers: -1
    p_muting: 0.0

model:
  type: AVMnistMixerMultiLoss
  dropout: 0.5
  modalities:
    classification:
      num_classes: 10
      classifier: MultilayerClassifier
      input_shape: [16, 49, 128]
      hidden_dims: [1024, 512, 256]
    image:
      block_type: MLPMixer
      in_channels: 1
      hidden_dim: 128
      patch_size: 4
      image_size: [28, 28]
      token_dim: 32
      channel_dim: 3072
      num_mixers: 4
    audio:
      block_type: MLPMixer
      in_channels: 1
      hidden_dim: 128
      patch_size: 16
      image_size: [112, 112]
      token_dim: 32
      channel_dim: 3072
      num_mixers: 4
    multimodal:
      block_type: MultimodalFusionMixer
      fusion_function: ExtraConcatFusion
      hidden_dim: 128
      token_dim: 32
      channel_dim: 3072
      num_mixers: 2
      num_modality: 2
      proj_modality_dim: 16
      modality_dim: 64
