train:
  tensorboard_path: ./logs/
  log_interval_steps: 10
  epochs: 30
  optimizer:
    lr: 5e-4
    betas: [0.9, 0.999]
    eps: 1e-8
    weight_decay: 0.0
  seed: 42
  monitor: val_loss
  monitor_mode: min

dataset:
  type: AVMnistDataModule
  params:
    data_dir: ../data/avmnist_orig/avmnist
    batch_size: 32
    num_workers: -1
    p_muting: 0.0

model:
  type: AVMnistMixerMultiLoss
  dropout: 0.5
  mute: image
  modalities:
    classification:
      num_classes: 10
    image:
      block_type: MLPMixer
      in_channels: 1
      hidden_dim: 128
      patch_size: 4
      image_size: [28, 28]
      token_dim: 32
      channel_dim: 3072
      num_mixers: 4
    audio:
      block_type: MLPMixer
      in_channels: 1
      hidden_dim: 128
      patch_size: 16
      image_size: [112, 112]
      token_dim: 32
      channel_dim: 3072
      num_mixers: 4
    multimodal:
      mod1_in: 128
      mod2_in: 128
      out_size: 128
      block_type: FusionMixer
      fusion_function: BiModalGatedUnit
      hidden_dim: 128
      token_dim: 32
      channel_dim: 3072
      num_mixers: 2
