train:
  tensorboard_path: ./logs/
  log_interval_steps: 10
  epochs: 100
  optimizer:
    lr: 1e-2
    betas: [0.9, 0.999]
    eps: 1e-8
    weight_decay: 0.0
    scheduler_patience: 3
  seed: 42
  monitor: val_loss
  monitor_mode: min

dataset:
  type: MMIMDBDataModule
  params:
    data_dir: ../data/mm_imdb
    batch_size: 32
    num_workers: -1
    max_seq_len: &max_seq_len 160

    projection:
      num_hashes: 64
      feature_size: &feature_size 1024
      window_size: &window_size 1

    vocab:
      tokenizer_type: wordpiece
      tokenizer:
        vocab: ./wordpiece/mbert_vocab.txt
        lowercase: false
        strip_accents: false
        clean_text: false
      vocab_path: vocab.npy

model:
  type: MMIMDBMixerMultiLoss
  dropout: 0.3
  modalities:
    classification:
      num_classes: 23
      classifier: StandardClassifier
      input_shape: [16, 49, 256]
      hidden_dims: [1024, 512, 256, 32]
    image:
      block_type: HyperMixer
      in_channels: 3
      hidden_dim: 256
      patch_size: 16
      image_size: [160, 256]
      channel_dim: 3072
      num_mixers: 4
      num_heads: 4
    text:
      block_type: PNLPMixer
      max_seq_len: *max_seq_len
      mlp_hidden_dim: 512
      bottleneck_window_size: *window_size
      bottleneck_features_size: *feature_size
      in_channels: 1
      hidden_dim: 256
      num_mixers: 4
    multimodal:
      block_type: FusionMixer
      fusion_function: ConcatFusion
      hidden_dim: 256
      token_dim: 32
      channel_dim: 3072
      num_mixers: 2
      num_modality: 2
      proj_modality_dim: 16
      modality_dim: 64
